
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-chumper-cn-v1-knfunction
  failurePolicy: Fail
  name: mknfunction.kb.io
  rules:
  - apiGroups:
    - app.chumper.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - knfunctions

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-chumper-cn-v1-knfunction
  failurePolicy: Fail
  name: vknfunction.kb.io
  rules:
  - apiGroups:
    - app.chumper.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - knfunctions
