# permissions for end users to view knfunctions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knfunction-viewer-role
rules:
- apiGroups:
  - app.chumper.cn
  resources:
  - knfunctions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.chumper.cn
  resources:
  - knfunctions/status
  verbs:
  - get
